feedweb/urls.py
from django.conf.urls import url

from . import views

app_name = 'feedweb'
urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^lang/(?P<lang>\w+)$', views.langView, name='LangView'),
    url(r'^cat/(?P<cat>[0-9]+)$', views.categoryView, name='CatView'),
    url(r'^(?P<feedid>[0-9]+)$', views.feedView, name='FeedView'),
]

newswire/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
                  url(r'^admin/', admin.site.urls),
                  url(r'^feed/', include('feedweb.urls')),
                  url(r'^chaining/', include('smart_selects.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

feedweb/models.py
from django.db import models
from smart_selects.db_fields import ChainedForeignKey


# Create your models here.
class FeedLanguage(models.Model):
    feed_language_code = models.CharField(max_length=4, unique=True)
    feed_language_name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.feed_language_code


class FeedCategory(models.Model):
    class Meta:
        unique_together = (('feed_category_name', 'feed_category_lang'),)

    feed_category_name = models.CharField(max_length=20)
    feed_category_lang = models.ForeignKey(FeedLanguage, on_delete=models.CASCADE)

    def __str__(self):
        return self.feed_category_name + " " +self.feed_category_lang.feed_language_code


class Feed(models.Model):
    title = models.CharField(max_length=250)
    pub_date = models.DateTimeField('pub_date', auto_now_add=True)
    feed_language = models.ForeignKey(FeedLanguage, on_delete=models.CASCADE)
    # feed_category = models.ForeignKey(FeedCategory, on_delete=models.CASCADE)
    feed_category = ChainedForeignKey(FeedCategory, chained_field="feed_language", chained_model_field="feed_category_lang", show_all=False, auto_choose=True, sort=True)

    def __str__(self):
        return self.title


class Section(models.Model):
    section_title = models.CharField(max_length=250, blank=True)
    section_body = models.TextField(max_length=5000, blank=True)
    section_video_url = models.URLField(max_length=2000, blank=True)
    section_image = models.ImageField(upload_to='img/%Y/%m/%d', blank=True)
    feed = models.ForeignKey(Feed, on_delete=models.CASCADE)

feedweb/views.py
from django.shortcuts import render
from django.utils import timezone

from .models import FeedCategory, Feed, Section, FeedLanguage


def home(request):
    return index(request, lang='EN', cat=0, feedid=0)


def categoryView(request, cat):
    lang = FeedCategory.objects.get(pk=cat).feed_category_lang.feed_language_code
    return index(request, cat=cat, lang=lang, feedid=0)


def langView(request, lang):
    return index(request, lang=lang, cat=0, feedid=0)


def feedView(request, feedid):
    lang = Feed.objects.get(pk=feedid).feed_language.feed_language_code
    return index(request, lang=lang, cat=0, feedid=feedid)


def index(request, lang, cat, feedid):
    categories = FeedCategory.objects.filter(feed_category_lang__feed_language_code=lang)
    if feedid:
        feed = Feed.objects.get(pk=feedid)
        feeds = Feed.objects.filter(feed_category_id=feed.feed_category.id, feed_language_id=feed.feed_language.id)[:5]
    elif cat:
        feeds = Feed.objects.filter(feed_category_id=cat, feed_language__feed_language_code=lang)[
                :5]
        feed = feeds[0]
    else:
        feeds = Feed.objects.filter(feed_language__feed_language_code=lang)[:5]
        feed = feeds[0]

    feed_sections = Section.objects.filter(feed_id=feed.id)
    languages = FeedLanguage.objects.all()

    context = {
        'categories': categories,
        'feeds': feeds,
        'feed': feed,
        'feed_sections': feed_sections,
        'languages': languages,
    }
    return render(request, 'feedweb/index.html', context)

feedweb/templates/feedweb/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>NewsWire</title>
    <link rel="stylesheet" type="text/css" href="https://bootswatch.com/slate/bootstrap.min.css"/>
    <script
            src="https://code.jquery.com/jquery-3.2.1.min.js"
            integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
            crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</head>
<body>

<div class="container-fluid">
    <div class="col-lg-1 col-offset-6 centered">
        <H1>KinyMony</H1>
    </div>
</div>

<nav class="navbar navbar-default">
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        {% if categories %}
            <ul class="nav navbar-nav">
                {% for item in categories %}
                    <li class="active"><a href="{% url 'feedweb:CatView' item.id %}">{{ item.feed_category_name }}</a>
                    </li>
                {% endfor %}
            </ul>
        {% endif %}
        <ul class="nav navbar-nav navbar-right">
            <div class="dropdown">
                <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">Select Language
                    <span class="caret"></span></button>
                <ul class="dropdown-menu">
                    {% for lang in languages %}<li><a href="{% url 'feedweb:LangView' lang.feed_language_code %}">{{ lang.feed_language_name }}</a></li>{% endfor %}
                </ul>
            </div>
        </ul>
    </div>
</nav>

<div class="container-fluid">
    <div class="col-sm-12 col-md-8">
        <div class="jumbotron">
            <h1>{{ feed.title }}</h1>
            {% for section in feed_sections %}
                {% if section.section_title %}<h2>{{ section.section_title }}</h2>{% endif %}
                {% if section.section_body %}
                    <p1>{{ section.section_body }}</p1>{% endif %}
                <br/>
                {% if section.section_image %}<img src="{{ section.section_image.url }}" height="420" width="600"/>
                {% endif %}
                <br/>
                {% if section.section_video_url %}
                    <iframe width="420" height="315" src="{{ section.section_video_url }}"></iframe>{% endif %}
            {% endfor %}
        </div>
    </div>
    <div class="col-sm-12 col-md-4">
        {% if feeds %}
            <div class="list-group">
                {% for item in feeds %}
                    <a href="{% url 'feedweb:FeedView' item.id %}" class="list-group-item active">
                        {{ item.title }}
                    </a>
                {% endfor %}
            </div>
        {% endif %}
    </div>
</div>

</body>
</html>